<?php
/**
 * ACFE Flexible Content Page Builder
 * 
 * Installation:
 * 1. Install ACF Extended plugin (free): https://wordpress.org/plugins/acf-extended/
 * 2. Add this code to functions.php or import the JSON file below
 * 3. Assign to your page template
 * 
 * Features:
 * - Drag & drop module reordering
 * - Add/remove modules dynamically
 * - Clone/duplicate modules
 * - Live preview in backend (with ACFE)
 * - Collapse/expand modules
 */

if( function_exists('acf_add_local_field_group') ):

// Register Module Settings Clone Group
acf_add_local_field_group(array(
  'key' => 'group_module_settings',
  'title' => 'Module Settings (Clone)',
  'fields' => array(
    array(
      'key' => 'field_module_settings_tabs',
      'label' => 'Module Settings',
      'name' => '',
      'type' => 'tab',
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_module_general_tab',
      'label' => 'General',
      'name' => '',
      'type' => 'tab',
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_module_html_id',
      'label' => 'HTML ID',
      'name' => 'module_html_id',
      'type' => 'text',
      'instructions' => 'Unique identifier for this module (e.g., "about-section"). Used for anchor links.',
      'wrapper' => array('width' => '50'),
    ),
    array(
      'key' => 'field_module_custom_classes',
      'label' => 'Custom CSS Classes',
      'name' => 'module_custom_classes',
      'type' => 'text',
      'instructions' => 'Space-separated CSS classes.',
      'wrapper' => array('width' => '50'),
    ),
    array(
      'key' => 'field_module_spacing_tab',
      'label' => 'Spacing',
      'name' => '',
      'type' => 'tab',
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_module_padding_top',
      'label' => 'Padding Top',
      'name' => 'module_padding_top',
      'type' => 'select',
      'choices' => array(
        '' => 'Default',
        '0' => 'None (0)',
        '20' => 'XS (20px)',
        '40' => 'SM (40px)',
        '60' => 'MD (60px)',
        '80' => 'LG (80px)',
        '120' => 'XL (120px)',
        '160' => '2XL (160px)',
      ),
      'wrapper' => array('width' => '25'),
    ),
    array(
      'key' => 'field_module_padding_bottom',
      'label' => 'Padding Bottom',
      'name' => 'module_padding_bottom',
      'type' => 'select',
      'choices' => array(
        '' => 'Default',
        '0' => 'None (0)',
        '20' => 'XS (20px)',
        '40' => 'SM (40px)',
        '60' => 'MD (60px)',
        '80' => 'LG (80px)',
        '120' => 'XL (120px)',
        '160' => '2XL (160px)',
      ),
      'wrapper' => array('width' => '25'),
    ),
    array(
      'key' => 'field_module_margin_top',
      'label' => 'Margin Top',
      'name' => 'module_margin_top',
      'type' => 'select',
      'choices' => array(
        '' => 'Default',
        '0' => 'None (0)',
        '20' => 'XS (20px)',
        '40' => 'SM (40px)',
        '60' => 'MD (60px)',
        '80' => 'LG (80px)',
        '120' => 'XL (120px)',
        '160' => '2XL (160px)',
      ),
      'wrapper' => array('width' => '25'),
    ),
    array(
      'key' => 'field_module_margin_bottom',
      'label' => 'Margin Bottom',
      'name' => 'module_margin_bottom',
      'type' => 'select',
      'choices' => array(
        '' => 'Default',
        '0' => 'None (0)',
        '20' => 'XS (20px)',
        '40' => 'SM (40px)',
        '60' => 'MD (60px)',
        '80' => 'LG (80px)',
        '120' => 'XL (120px)',
        '160' => '2XL (160px)',
      ),
      'wrapper' => array('width' => '25'),
    ),
    array(
      'key' => 'field_module_background_tab',
      'label' => 'Background',
      'name' => '',
      'type' => 'tab',
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_module_background_type',
      'label' => 'Background Type',
      'name' => 'module_background_type',
      'type' => 'select',
      'choices' => array(
        'none' => 'None',
        'color' => 'Solid Color',
        'gradient' => 'Gradient',
        'image' => 'Image',
        'video' => 'Video',
      ),
      'default_value' => 'none',
    ),
    array(
      'key' => 'field_module_background_color',
      'label' => 'Background Color',
      'name' => 'module_background_color',
      'type' => 'color_picker',
      'default_value' => '#ffffff',
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_module_background_type',
            'operator' => '==',
            'value' => 'color',
          ),
        ),
      ),
    ),
    array(
      'key' => 'field_module_background_gradient',
      'label' => 'Gradient',
      'name' => 'module_background_gradient',
      'type' => 'group',
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_module_background_type',
            'operator' => '==',
            'value' => 'gradient',
          ),
        ),
      ),
      'sub_fields' => array(
        array(
          'key' => 'field_gradient_color_1',
          'label' => 'Color 1',
          'name' => 'color_1',
          'type' => 'color_picker',
          'default_value' => '#ffffff',
          'wrapper' => array('width' => '33'),
        ),
        array(
          'key' => 'field_gradient_color_2',
          'label' => 'Color 2',
          'name' => 'color_2',
          'type' => 'color_picker',
          'default_value' => '#f0f0f0',
          'wrapper' => array('width' => '33'),
        ),
        array(
          'key' => 'field_gradient_direction',
          'label' => 'Direction',
          'name' => 'direction',
          'type' => 'select',
          'choices' => array(
            'to bottom' => 'Top to Bottom',
            'to top' => 'Bottom to Top',
            'to right' => 'Left to Right',
            'to left' => 'Right to Left',
            '135deg' => 'Diagonal (↘)',
            '45deg' => 'Diagonal (↗)',
          ),
          'default_value' => 'to bottom',
          'wrapper' => array('width' => '34'),
        ),
      ),
    ),
    array(
      'key' => 'field_module_background_image',
      'label' => 'Background Image',
      'name' => 'module_background_image',
      'type' => 'image',
      'return_format' => 'array',
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_module_background_type',
            'operator' => '==',
            'value' => 'image',
          ),
        ),
      ),
    ),
    array(
      'key' => 'field_module_background_image_settings',
      'label' => 'Image Settings',
      'name' => 'module_background_image_settings',
      'type' => 'group',
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_module_background_type',
            'operator' => '==',
            'value' => 'image',
          ),
        ),
      ),
      'sub_fields' => array(
        array(
          'key' => 'field_bg_image_size',
          'label' => 'Size',
          'name' => 'size',
          'type' => 'select',
          'choices' => array(
            'cover' => 'Cover',
            'contain' => 'Contain',
            'auto' => 'Auto',
          ),
          'default_value' => 'cover',
          'wrapper' => array('width' => '33'),
        ),
        array(
          'key' => 'field_bg_image_position',
          'label' => 'Position',
          'name' => 'position',
          'type' => 'select',
          'choices' => array(
            'center center' => 'Center',
            'top center' => 'Top',
            'bottom center' => 'Bottom',
            'center left' => 'Left',
            'center right' => 'Right',
          ),
          'default_value' => 'center center',
          'wrapper' => array('width' => '33'),
        ),
        array(
          'key' => 'field_bg_image_repeat',
          'label' => 'Repeat',
          'name' => 'repeat',
          'type' => 'select',
          'choices' => array(
            'no-repeat' => 'No Repeat',
            'repeat' => 'Repeat',
            'repeat-x' => 'Repeat X',
            'repeat-y' => 'Repeat Y',
          ),
          'default_value' => 'no-repeat',
          'wrapper' => array('width' => '34'),
        ),
        array(
          'key' => 'field_bg_image_overlay',
          'label' => 'Overlay Color',
          'name' => 'overlay',
          'type' => 'color_picker',
          'enable_opacity' => 1,
          'wrapper' => array('width' => '50'),
        ),
        array(
          'key' => 'field_bg_image_parallax',
          'label' => 'Parallax Effect',
          'name' => 'parallax',
          'type' => 'true_false',
          'default_value' => 0,
          'wrapper' => array('width' => '50'),
        ),
      ),
    ),
    array(
      'key' => 'field_module_background_video',
      'label' => 'Background Video',
      'name' => 'module_background_video',
      'type' => 'group',
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_module_background_type',
            'operator' => '==',
            'value' => 'video',
          ),
        ),
      ),
      'sub_fields' => array(
        array(
          'key' => 'field_bg_video_url',
          'label' => 'Video URL',
          'name' => 'url',
          'type' => 'url',
          'wrapper' => array('width' => '100'),
        ),
        array(
          'key' => 'field_bg_video_fallback',
          'label' => 'Fallback Image',
          'name' => 'fallback',
          'type' => 'image',
          'return_format' => 'array',
          'wrapper' => array('width' => '50'),
        ),
        array(
          'key' => 'field_bg_video_overlay',
          'label' => 'Overlay Color',
          'name' => 'overlay',
          'type' => 'color_picker',
          'enable_opacity' => 1,
          'wrapper' => array('width' => '50'),
        ),
      ),
    ),
    array(
      'key' => 'field_module_animation_tab',
      'label' => 'Animation',
      'name' => '',
      'type' => 'tab',
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_module_animation_enabled',
      'label' => 'Enable Animation',
      'name' => 'module_animation_enabled',
      'type' => 'true_false',
      'default_value' => 0,
    ),
    array(
      'key' => 'field_module_animation_type',
      'label' => 'Animation Type',
      'name' => 'module_animation_type',
      'type' => 'select',
      'choices' => array(
        'fade' => 'Fade In',
        'fadeUp' => 'Fade Up',
        'fadeDown' => 'Fade Down',
        'fadeLeft' => 'Fade Left',
        'fadeRight' => 'Fade Right',
        'scale' => 'Scale In',
        'slideUp' => 'Slide Up',
        'slideDown' => 'Slide Down',
        'slideLeft' => 'Slide Left',
        'slideRight' => 'Slide Right',
      ),
      'default_value' => 'fadeUp',
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_module_animation_enabled',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array('width' => '50'),
    ),
    array(
      'key' => 'field_module_animation_duration',
      'label' => 'Duration (seconds)',
      'name' => 'module_animation_duration',
      'type' => 'number',
      'default_value' => 1,
      'min' => 0.1,
      'max' => 5,
      'step' => 0.1,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_module_animation_enabled',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array('width' => '25'),
    ),
    array(
      'key' => 'field_module_animation_delay',
      'label' => 'Delay (seconds)',
      'name' => 'module_animation_delay',
      'type' => 'number',
      'default_value' => 0,
      'min' => 0,
      'max' => 5,
      'step' => 0.1,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_module_animation_enabled',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array('width' => '25'),
    ),
    array(
      'key' => 'field_module_animation_easing',
      'label' => 'Easing',
      'name' => 'module_animation_easing',
      'type' => 'select',
      'choices' => array(
        'power1.out' => 'Power1 Out (Gentle)',
        'power2.out' => 'Power2 Out (Medium)',
        'power3.out' => 'Power3 Out (Strong)',
        'power4.out' => 'Power4 Out (Very Strong)',
        'back.out(1.7)' => 'Back Out (Overshoot)',
        'elastic.out(1, 0.3)' => 'Elastic Out (Bounce)',
        'bounce.out' => 'Bounce Out',
      ),
      'default_value' => 'power2.out',
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_module_animation_enabled',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array('width' => '50'),
    ),
    array(
      'key' => 'field_module_animation_stagger',
      'label' => 'Stagger Children',
      'name' => 'module_animation_stagger',
      'type' => 'number',
      'default_value' => 0,
      'min' => 0,
      'max' => 1,
      'step' => 0.05,
      'conditional_logic' => array(
        array(
          array(
            'field' => 'field_module_animation_enabled',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array('width' => '50'),
    ),
    array(
      'key' => 'field_module_visibility_tab',
      'label' => 'Visibility',
      'name' => '',
      'type' => 'tab',
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_module_visibility_desktop',
      'label' => 'Show on Desktop',
      'name' => 'module_visibility_desktop',
      'type' => 'true_false',
      'default_value' => 1,
      'wrapper' => array('width' => '33'),
    ),
    array(
      'key' => 'field_module_visibility_tablet',
      'label' => 'Show on Tablet',
      'name' => 'module_visibility_tablet',
      'type' => 'true_false',
      'default_value' => 1,
      'wrapper' => array('width' => '33'),
    ),
    array(
      'key' => 'field_module_visibility_mobile',
      'label' => 'Show on Mobile',
      'name' => 'module_visibility_mobile',
      'type' => 'true_false',
      'default_value' => 1,
      'wrapper' => array('width' => '34'),
    ),
    array(
      'key' => 'field_module_advanced_tab',
      'label' => 'Advanced',
      'name' => '',
      'type' => 'tab',
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array(
      'key' => 'field_module_container_width',
      'label' => 'Container Width',
      'name' => 'module_container_width',
      'type' => 'select',
      'choices' => array(
        '' => 'Default',
        'full' => 'Full Width (100%)',
        'wide' => 'Wide (1400px)',
        'standard' => 'Standard (1200px)',
        'narrow' => 'Narrow (960px)',
        'tight' => 'Tight (720px)',
      ),
      'wrapper' => array('width' => '50'),
    ),
    array(
      'key' => 'field_module_z_index',
      'label' => 'Z-Index',
      'name' => 'module_z_index',
      'type' => 'number',
      'min' => -1,
      'max' => 9999,
      'wrapper' => array('width' => '50'),
    ),
    array(
      'key' => 'field_module_custom_css',
      'label' => 'Custom CSS',
      'name' => 'module_custom_css',
      'type' => 'textarea',
      'instructions' => 'Advanced: Add custom CSS for this module only.',
      'rows' => 6,
    ),
  ),
  'acfe_display_title' => '',
  'acfe_autosync' => array('json'),
));

// Page Builder Field Group
acf_add_local_field_group(array(
  'key' => 'group_page_builder',
  'title' => 'Page Builder',
  'fields' => array(
    array(
      'key' => 'field_page_builder',
      'label' => 'Page Modules',
      'name' => 'page_builder',
      'type' => 'flexible_content',
      'button_label' => 'Add Module',
      'acfe_flexible_stylised_button' => true,
      'acfe_flexible_hide_empty_message' => false,
      'acfe_flexible_empty_message' => 'Click "Add Module" to start building your page',
      'acfe_flexible_layouts_thumbnails' => true,
      'acfe_flexible_layouts_settings' => true,
      'acfe_flexible_layouts_ajax' => false,
      'acfe_flexible_add_actions' => array('title'),
      'acfe_flexible_remove_button' => array('default'),
      'acfe_flexible_layouts_state' => 'collapse',
      'acfe_flexible_modal_edition' => array(
        'acfe_flexible_modal_edition_enabled' => '1',
        'acfe_flexible_modal_edition_size' => 'large',
      ),
      'layouts' => array(
        
        // Header Layout
        'layout_header' => array(
          'key' => 'layout_header',
          'name' => 'header',
          'label' => 'Header',
          'display' => 'block',
          'acfe_flexible_render_template' => get_template_directory() . '/modules/header.php',
          'acfe_flexible_render_style' => get_template_directory() . '/style.css',
          'acfe_flexible_thumbnail' => false,
          'sub_fields' => array(
            array(
              'key' => 'field_header_settings_fc',
              'label' => 'Module Settings',
              'name' => 'module_settings',
              'type' => 'clone',
              'clone' => array('group_module_settings'),
              'display' => 'group',
              'layout' => 'block',
              'prefix_label' => 0,
              'prefix_name' => 0,
            ),
            array(
              'key' => 'field_header_logo_images_fc',
              'label' => 'Logo Images',
              'name' => 'header_logo_images',
              'type' => 'gallery',
              'return_format' => 'array',
            ),
            array(
              'key' => 'field_header_navigation_fc',
              'label' => 'Navigation Items',
              'name' => 'header_navigation',
              'type' => 'repeater',
              'layout' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_nav_label_fc',
                  'label' => 'Label',
                  'name' => 'label',
                  'type' => 'text',
                ),
                array(
                  'key' => 'field_nav_has_mega_menu_fc',
                  'label' => 'Has Mega Menu',
                  'name' => 'has_mega_menu',
                  'type' => 'true_false',
                  'default_value' => 0,
                ),
                array(
                  'key' => 'field_nav_mega_menu_columns_fc',
                  'label' => 'Mega Menu Columns',
                  'name' => 'mega_menu_columns',
                  'type' => 'repeater',
                  'conditional_logic' => array(
                    array(
                      array(
                        'field' => 'field_nav_has_mega_menu_fc',
                        'operator' => '==',
                        'value' => '1',
                      ),
                    ),
                  ),
                  'sub_fields' => array(
                    array(
                      'key' => 'field_mega_column_title_fc',
                      'label' => 'Column Title',
                      'name' => 'title',
                      'type' => 'text',
                    ),
                    array(
                      'key' => 'field_mega_column_links_fc',
                      'label' => 'Links',
                      'name' => 'links',
                      'type' => 'repeater',
                      'sub_fields' => array(
                        array(
                          'key' => 'field_mega_link_text_fc',
                          'label' => 'Text',
                          'name' => 'text',
                          'type' => 'text',
                        ),
                        array(
                          'key' => 'field_mega_link_url_fc',
                          'label' => 'URL',
                          'name' => 'url',
                          'type' => 'url',
                        ),
                      ),
                    ),
                  ),
                ),
                array(
                  'key' => 'field_nav_has_flyout_fc',
                  'label' => 'Has Flyout Menu',
                  'name' => 'has_flyout',
                  'type' => 'true_false',
                  'default_value' => 0,
                ),
                array(
                  'key' => 'field_nav_flyout_links_fc',
                  'label' => 'Flyout Links',
                  'name' => 'flyout_links',
                  'type' => 'repeater',
                  'conditional_logic' => array(
                    array(
                      array(
                        'field' => 'field_nav_has_flyout_fc',
                        'operator' => '==',
                        'value' => '1',
                      ),
                    ),
                  ),
                  'sub_fields' => array(
                    array(
                      'key' => 'field_flyout_link_text_fc',
                      'label' => 'Text',
                      'name' => 'text',
                      'type' => 'text',
                    ),
                    array(
                      'key' => 'field_flyout_link_url_fc',
                      'label' => 'URL',
                      'name' => 'url',
                      'type' => 'url',
                    ),
                  ),
                ),
              ),
            ),
            array(
              'key' => 'field_header_contact_button_text_fc',
              'label' => 'Contact Button Text',
              'name' => 'header_contact_button_text',
              'type' => 'text',
              'default_value' => 'Contact us',
            ),
            array(
              'key' => 'field_header_search_icon_fc',
              'label' => 'Search Icon',
              'name' => 'header_search_icon',
              'type' => 'image',
              'return_format' => 'array',
            ),
            array(
              'key' => 'field_header_menu_icon_fc',
              'label' => 'Mobile Menu Icon',
              'name' => 'header_menu_icon',
              'type' => 'image',
              'return_format' => 'array',
            ),
          ),
        ),
        
        // Hero Layout
        'layout_hero' => array(
          'key' => 'layout_hero',
          'name' => 'hero',
          'label' => 'Hero Banner',
          'display' => 'block',
          'acfe_flexible_render_template' => get_template_directory() . '/modules/hero.php',
          'acfe_flexible_render_style' => get_template_directory() . '/style.css',
          'sub_fields' => array(
            array(
              'key' => 'field_hero_settings_fc',
              'label' => 'Module Settings',
              'name' => 'module_settings',
              'type' => 'clone',
              'clone' => array('group_module_settings'),
              'display' => 'group',
              'layout' => 'block',
              'prefix_label' => 0,
              'prefix_name' => 0,
            ),
            array(
              'key' => 'field_hero_video_url_fc',
              'label' => 'Video URL',
              'name' => 'hero_video_url',
              'type' => 'url',
            ),
            array(
              'key' => 'field_hero_title_fc',
              'label' => 'Title',
              'name' => 'hero_title',
              'type' => 'textarea',
              'rows' => 3,
            ),
            array(
              'key' => 'field_hero_subtitle_fc',
              'label' => 'Subtitle',
              'name' => 'hero_subtitle',
              'type' => 'text',
            ),
            array(
              'key' => 'field_hero_primary_button_fc',
              'label' => 'Primary Button',
              'name' => 'hero_primary_button',
              'type' => 'group',
              'sub_fields' => array(
                array(
                  'key' => 'field_hero_primary_text_fc',
                  'label' => 'Text',
                  'name' => 'text',
                  'type' => 'text',
                ),
                array(
                  'key' => 'field_hero_primary_url_fc',
                  'label' => 'URL',
                  'name' => 'url',
                  'type' => 'url',
                ),
              ),
            ),
            array(
              'key' => 'field_hero_secondary_button_fc',
              'label' => 'Secondary Button',
              'name' => 'hero_secondary_button',
              'type' => 'group',
              'sub_fields' => array(
                array(
                  'key' => 'field_hero_secondary_text_fc',
                  'label' => 'Text',
                  'name' => 'text',
                  'type' => 'text',
                ),
                array(
                  'key' => 'field_hero_secondary_url_fc',
                  'label' => 'URL',
                  'name' => 'url',
                  'type' => 'url',
                ),
              ),
            ),
          ),
        ),
        
        // Logo Slider Layout
        'layout_logo_slider' => array(
          'key' => 'layout_logo_slider',
          'name' => 'logo_slider',
          'label' => 'Logo Slider',
          'display' => 'block',
          'acfe_flexible_render_template' => get_template_directory() . '/modules/logo-slider.php',
          'acfe_flexible_render_style' => get_template_directory() . '/style.css',
          'sub_fields' => array(
            array(
              'key' => 'field_logo_slider_settings_fc',
              'label' => 'Module Settings',
              'name' => 'module_settings',
              'type' => 'clone',
              'clone' => array('group_module_settings'),
              'display' => 'group',
              'layout' => 'block',
              'prefix_label' => 0,
              'prefix_name' => 0,
            ),
            array(
              'key' => 'field_logo_slider_logos_fc',
              'label' => 'Logos',
              'name' => 'logo_slider_logos',
              'type' => 'gallery',
              'return_format' => 'array',
            ),
          ),
        ),
        
        // About Layout
        'layout_about' => array(
          'key' => 'layout_about',
          'name' => 'about',
          'label' => 'About Section',
          'display' => 'block',
          'acfe_flexible_render_template' => get_template_directory() . '/modules/about.php',
          'acfe_flexible_render_style' => get_template_directory() . '/style.css',
          'sub_fields' => array(
            array(
              'key' => 'field_about_settings_fc',
              'label' => 'Module Settings',
              'name' => 'module_settings',
              'type' => 'clone',
              'clone' => array('group_module_settings'),
              'display' => 'group',
              'layout' => 'block',
              'prefix_label' => 0,
              'prefix_name' => 0,
            ),
            array(
              'key' => 'field_about_background_image_fc',
              'label' => 'Background Image',
              'name' => 'about_background_image',
              'type' => 'image',
              'return_format' => 'array',
            ),
            array(
              'key' => 'field_about_label_fc',
              'label' => 'Label',
              'name' => 'about_label',
              'type' => 'text',
            ),
            array(
              'key' => 'field_about_title_fc',
              'label' => 'Title',
              'name' => 'about_title',
              'type' => 'text',
            ),
            array(
              'key' => 'field_about_description_fc',
              'label' => 'Description',
              'name' => 'about_description',
              'type' => 'wysiwyg',
              'tabs' => 'all',
              'toolbar' => 'basic',
            ),
            array(
              'key' => 'field_about_button_text_fc',
              'label' => 'Button Text',
              'name' => 'about_button_text',
              'type' => 'text',
            ),
            array(
              'key' => 'field_about_icon_images_fc',
              'label' => 'Icon Images',
              'name' => 'about_icon_images',
              'type' => 'gallery',
              'return_format' => 'array',
            ),
          ),
        ),
        
        // Clients Grid Layout
        'layout_clients_grid' => array(
          'key' => 'layout_clients_grid',
          'name' => 'clients_grid',
          'label' => 'Clients Grid',
          'display' => 'block',
          'acfe_flexible_render_template' => get_template_directory() . '/modules/clients-grid.php',
          'acfe_flexible_render_style' => get_template_directory() . '/style.css',
          'sub_fields' => array(
            array(
              'key' => 'field_clients_grid_settings_fc',
              'label' => 'Module Settings',
              'name' => 'module_settings',
              'type' => 'clone',
              'clone' => array('group_module_settings'),
              'display' => 'group',
              'layout' => 'block',
              'prefix_label' => 0,
              'prefix_name' => 0,
            ),
            array(
              'key' => 'field_clients_grid_title_fc',
              'label' => 'Title',
              'name' => 'clients_grid_title',
              'type' => 'text',
            ),
            array(
              'key' => 'field_clients_grid_cards_fc',
              'label' => 'Client Cards',
              'name' => 'clients_grid_cards',
              'type' => 'repeater',
              'layout' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_client_card_image_fc',
                  'label' => 'Image',
                  'name' => 'image',
                  'type' => 'image',
                  'return_format' => 'array',
                ),
                array(
                  'key' => 'field_client_card_title_fc',
                  'label' => 'Title',
                  'name' => 'title',
                  'type' => 'text',
                ),
              ),
            ),
          ),
        ),
        
        // Sectors Slider Layout
        'layout_sectors' => array(
          'key' => 'layout_sectors',
          'name' => 'sectors_slider',
          'label' => 'Sectors Slider',
          'display' => 'block',
          'acfe_flexible_render_template' => get_template_directory() . '/modules/sectors-slider.php',
          'acfe_flexible_render_style' => get_template_directory() . '/style.css',
          'sub_fields' => array(
            array(
              'key' => 'field_sectors_settings_fc',
              'label' => 'Module Settings',
              'name' => 'module_settings',
              'type' => 'clone',
              'clone' => array('group_module_settings'),
              'display' => 'group',
              'layout' => 'block',
              'prefix_label' => 0,
              'prefix_name' => 0,
            ),
            array(
              'key' => 'field_sectors_label_fc',
              'label' => 'Label',
              'name' => 'sectors_label',
              'type' => 'text',
            ),
            array(
              'key' => 'field_sectors_title_fc',
              'label' => 'Title',
              'name' => 'sectors_title',
              'type' => 'text',
            ),
            array(
              'key' => 'field_sectors_items_fc',
              'label' => 'Sector Items',
              'name' => 'sectors_items',
              'type' => 'repeater',
              'layout' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_sector_icon_fc',
                  'label' => 'Icon',
                  'name' => 'icon',
                  'type' => 'image',
                  'return_format' => 'array',
                ),
                array(
                  'key' => 'field_sector_name_fc',
                  'label' => 'Name',
                  'name' => 'name',
                  'type' => 'text',
                ),
                array(
                  'key' => 'field_sector_content_title_fc',
                  'label' => 'Content Title',
                  'name' => 'content_title',
                  'type' => 'text',
                ),
                array(
                  'key' => 'field_sector_content_description_fc',
                  'label' => 'Content Description',
                  'name' => 'content_description',
                  'type' => 'textarea',
                ),
                array(
                  'key' => 'field_sector_content_image_fc',
                  'label' => 'Content Image',
                  'name' => 'content_image',
                  'type' => 'image',
                  'return_format' => 'array',
                ),
              ),
            ),
            array(
              'key' => 'field_sectors_button_text_fc',
              'label' => 'Button Text',
              'name' => 'sectors_button_text',
              'type' => 'text',
            ),
          ),
        ),
        
        // Trusted By Layout
        'layout_trusted_by' => array(
          'key' => 'layout_trusted_by',
          'name' => 'trusted_by',
          'label' => 'Trusted By',
          'display' => 'block',
          'acfe_flexible_render_template' => get_template_directory() . '/modules/trusted-by.php',
          'acfe_flexible_render_style' => get_template_directory() . '/style.css',
          'sub_fields' => array(
            array(
              'key' => 'field_trusted_by_settings_fc',
              'label' => 'Module Settings',
              'name' => 'module_settings',
              'type' => 'clone',
              'clone' => array('group_module_settings'),
              'display' => 'group',
              'layout' => 'block',
              'prefix_label' => 0,
              'prefix_name' => 0,
            ),
            array(
              'key' => 'field_trusted_by_title_fc',
              'label' => 'Title',
              'name' => 'trusted_by_title',
              'type' => 'text',
            ),
            array(
              'key' => 'field_trusted_by_logos_fc',
              'label' => 'Logos',
              'name' => 'trusted_by_logos',
              'type' => 'gallery',
              'return_format' => 'array',
            ),
          ),
        ),
        
        // Fire Systems Layout
        'layout_fire_systems' => array(
          'key' => 'layout_fire_systems',
          'name' => 'fire_systems',
          'label' => 'Fire Systems',
          'display' => 'block',
          'acfe_flexible_render_template' => get_template_directory() . '/modules/fire-systems.php',
          'acfe_flexible_render_style' => get_template_directory() . '/style.css',
          'sub_fields' => array(
            array(
              'key' => 'field_fire_systems_settings_fc',
              'label' => 'Module Settings',
              'name' => 'module_settings',
              'type' => 'clone',
              'clone' => array('group_module_settings'),
              'display' => 'group',
              'layout' => 'block',
              'prefix_label' => 0,
              'prefix_name' => 0,
            ),
            array(
              'key' => 'field_fire_systems_title_fc',
              'label' => 'Title',
              'name' => 'fire_systems_title',
              'type' => 'text',
            ),
            array(
              'key' => 'field_fire_systems_cards_fc',
              'label' => 'System Cards',
              'name' => 'fire_systems_cards',
              'type' => 'repeater',
              'layout' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_fire_system_icon_fc',
                  'label' => 'Icon',
                  'name' => 'icon',
                  'type' => 'image',
                  'return_format' => 'array',
                ),
                array(
                  'key' => 'field_fire_system_title_fc',
                  'label' => 'Title',
                  'name' => 'title',
                  'type' => 'text',
                ),
                array(
                  'key' => 'field_fire_system_arrow_icon_fc',
                  'label' => 'Arrow Icon',
                  'name' => 'arrow_icon',
                  'type' => 'image',
                  'return_format' => 'array',
                ),
              ),
            ),
          ),
        ),
        
        // Products Slider Layout
        'layout_products' => array(
          'key' => 'layout_products',
          'name' => 'products_slider',
          'label' => 'Products Slider',
          'display' => 'block',
          'acfe_flexible_render_template' => get_template_directory() . '/modules/products-slider.php',
          'acfe_flexible_render_style' => get_template_directory() . '/style.css',
          'sub_fields' => array(
            array(
              'key' => 'field_products_settings_fc',
              'label' => 'Module Settings',
              'name' => 'module_settings',
              'type' => 'clone',
              'clone' => array('group_module_settings'),
              'display' => 'group',
              'layout' => 'block',
              'prefix_label' => 0,
              'prefix_name' => 0,
            ),
            array(
              'key' => 'field_products_label_fc',
              'label' => 'Label',
              'name' => 'products_label',
              'type' => 'text',
            ),
            array(
              'key' => 'field_products_title_fc',
              'label' => 'Title',
              'name' => 'products_title',
              'type' => 'text',
            ),
            array(
              'key' => 'field_products_items_fc',
              'label' => 'Product Items',
              'name' => 'products_items',
              'type' => 'repeater',
              'layout' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_product_image_fc',
                  'label' => 'Image',
                  'name' => 'image',
                  'type' => 'image',
                  'return_format' => 'array',
                ),
                array(
                  'key' => 'field_product_title_fc',
                  'label' => 'Title',
                  'name' => 'title',
                  'type' => 'text',
                ),
                array(
                  'key' => 'field_product_description_fc',
                  'label' => 'Description',
                  'name' => 'description',
                  'type' => 'textarea',
                ),
                array(
                  'key' => 'field_product_button_text_fc',
                  'label' => 'Button Text',
                  'name' => 'button_text',
                  'type' => 'text',
                ),
              ),
            ),
          ),
        ),
        
        // Logos Slider Bottom Layout
        'layout_logos_slider_bottom' => array(
          'key' => 'layout_logos_slider_bottom',
          'name' => 'logos_slider_bottom',
          'label' => 'Logos Slider (Bottom)',
          'display' => 'block',
          'acfe_flexible_render_template' => get_template_directory() . '/modules/logos-slider.php',
          'acfe_flexible_render_style' => get_template_directory() . '/style.css',
          'sub_fields' => array(
            array(
              'key' => 'field_logos_slider_settings_fc',
              'label' => 'Module Settings',
              'name' => 'module_settings',
              'type' => 'clone',
              'clone' => array('group_module_settings'),
              'display' => 'group',
              'layout' => 'block',
              'prefix_label' => 0,
              'prefix_name' => 0,
            ),
            array(
              'key' => 'field_logos_slider_title_fc',
              'label' => 'Title',
              'name' => 'logos_slider_title',
              'type' => 'text',
            ),
            array(
              'key' => 'field_logos_slider_logos_bottom_fc',
              'label' => 'Logos',
              'name' => 'logos_slider_logos_bottom',
              'type' => 'gallery',
              'return_format' => 'array',
            ),
          ),
        ),
        
        // Footer Layout
        'layout_footer' => array(
          'key' => 'layout_footer',
          'name' => 'footer',
          'label' => 'Footer',
          'display' => 'block',
          'acfe_flexible_render_template' => get_template_directory() . '/modules/footer.php',
          'acfe_flexible_render_style' => get_template_directory() . '/style.css',
          'sub_fields' => array(
            array(
              'key' => 'field_footer_settings_fc',
              'label' => 'Module Settings',
              'name' => 'module_settings',
              'type' => 'clone',
              'clone' => array('group_module_settings'),
              'display' => 'group',
              'layout' => 'block',
              'prefix_label' => 0,
              'prefix_name' => 0,
            ),
            array(
              'key' => 'field_footer_logo_images_fc',
              'label' => 'Logo Images',
              'name' => 'footer_logo_images',
              'type' => 'gallery',
              'return_format' => 'array',
            ),
            array(
              'key' => 'field_footer_intro_text_fc',
              'label' => 'Intro Text',
              'name' => 'footer_intro_text',
              'type' => 'textarea',
            ),
            array(
              'key' => 'field_footer_accreditations_image_fc',
              'label' => 'Accreditations Image',
              'name' => 'footer_accreditations_image',
              'type' => 'image',
              'return_format' => 'array',
            ),
            array(
              'key' => 'field_footer_address_fc',
              'label' => 'Address',
              'name' => 'footer_address',
              'type' => 'textarea',
            ),
            array(
              'key' => 'field_footer_company_number_fc',
              'label' => 'Company Number',
              'name' => 'footer_company_number',
              'type' => 'text',
            ),
            array(
              'key' => 'field_footer_social_icons_fc',
              'label' => 'Social Icons',
              'name' => 'footer_social_icons',
              'type' => 'gallery',
              'return_format' => 'array',
            ),
            array(
              'key' => 'field_footer_columns_fc',
              'label' => 'Footer Columns',
              'name' => 'footer_columns',
              'type' => 'repeater',
              'layout' => 'block',
              'sub_fields' => array(
                array(
                  'key' => 'field_footer_column_title_fc',
                  'label' => 'Title',
                  'name' => 'title',
                  'type' => 'text',
                ),
                array(
                  'key' => 'field_footer_column_links_fc',
                  'label' => 'Links',
                  'name' => 'links',
                  'type' => 'repeater',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_footer_link_text_fc',
                      'label' => 'Text',
                      'name' => 'text',
                      'type' => 'text',
                    ),
                    array(
                      'key' => 'field_footer_link_url_fc',
                      'label' => 'URL',
                      'name' => 'url',
                      'type' => 'url',
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
        
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'page',
      ),
    ),
  ),
  'style' => 'seamless',
  'acfe_display_title' => '',
  'acfe_autosync' => array('json'),
  'acfe_form' => 0,
  'acfe_meta' => '',
  'acfe_note' => '',
));

endif;
